=== adzh2100/PawnshopCatalog/validation.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT pawnshop (classification, resources, pawns)>
<!-- CLASSIFICATION -->
<!ELEMENT classification (jewellery, electronics, antiques, art, precious_metals, vehicles)>
<!ELEMENT jewellery (resource_ref*)>
<!ELEMENT electronics (resource_ref*)>
<!ELEMENT antiques (resource_ref*)>
<!ELEMENT art (resource_ref*)>
<!ELEMENT precious_metals (resource_ref*)>
<!ELEMENT vehicles (resource_ref*)>
<!ELEMENT resource_ref EMPTY>
<!ATTLIST resource_ref ref IDREF #REQUIRED>
<!-- RESOURCES -->
<!ELEMENT resources (resource*)>
<!ELEMENT resource (type, pawn_ref, (author | manufacturer)?, model?, pawnshop_evaluation, description?, images)>
<!ATTLIST resource
    id ID #REQUIRED
    classification (Jewellery|Electronics|Antiques|Art|Precious_Metals) #REQUIRED
>
<!ELEMENT type (#PCDATA)>
<!ELEMENT pawn_ref EMPTY>
<!ATTLIST pawn_ref ref IDREF #REQUIRED>
<!ELEMENT author (#PCDATA)>
<!ELEMENT manufacturer (#PCDATA)>
<!ELEMENT model (#PCDATA)>
<!ELEMENT pawnshop_evaluation (currency, value)>
<!ELEMENT currency (#PCDATA)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT images (image*)>
<!ELEMENT image EMPTY>
<!ATTLIST image href ENTITY #REQUIRED>
<!NOTATION jpg PUBLIC "jpg viewer">
<!-- PAWNS -->
<!ELEMENT pawns (pawn*)>
<!ELEMENT pawn (amount_given, recipient_employee, submitter, term, created_at, updated_at)>
<!ATTLIST pawn
    id ID #REQUIRED
    status (Active|Pending|Settled|EMNR) #REQUIRED
>
<!-- EMNR <=> (expired, money not returned) -->
<!ELEMENT amount_given (currency, value)>
<!ELEMENT recipient_employee (name, surname, employee_id)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT surname (#PCDATA)>
<!ELEMENT employee_id (#PCDATA)>
<!ELEMENT submitter (name, surname, ucn, permanent_address, phone_number, id_card)>
<!ELEMENT ucn (#PCDATA)>
<!ELEMENT permanent_address (#PCDATA)>
<!ELEMENT phone_number (#PCDATA)>
<!ELEMENT id_card (#PCDATA)>
<!ELEMENT term (#PCDATA)>
<!ELEMENT created_at (#PCDATA)>
<!ELEMENT updated_at (#PCDATA)>

=== adzh2100/PawnshopCatalog/pawnshop.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE pawnshop SYSTEM "validation.dtd" [
    <!ENTITY goldChain SYSTEM "images/gold_chain.jpg" NDATA jpg>
    <!ENTITY necklace SYSTEM "images/necklace.jpg" NDATA jpg>
]>

<pawnshop>

    <classification>
        <jewellery>
            <resource_ref ref="J000001" />
            <resource_ref ref="J000002" />
        </jewellery>
        <electronics></electronics>
        <antiques></antiques>
        <art></art>
        <precious_metals></precious_metals>
        <vehicles></vehicles>
    </classification>


    <resources>
        <resource id="J000001" classification="Jewellery">
            <type>Gold Chain</type>
            <pawn_ref ref="P-J000001" />
            <pawnshop_evaluation>
                <currency>BGN</currency>
                <value>140.99</value>
            </pawnshop_evaluation>
            <description>A 24 karat gold chain</description>
            <images>
                <image href="goldChain" />
            </images>
        </resource>
        <resource id="J000002" classification="Jewellery">
            <type>Necklace</type>
            <pawn_ref ref="P-J000002" />
            <pawnshop_evaluation>
                <currency>BGN</currency>
                <value>120.22</value>
            </pawnshop_evaluation>
            <description>A brand new golden necklace that belonged to Cleopatra's cat </description>
            <images>
                <image href="necklace" />
            </images>
        </resource>
    </resources>


    <pawns>
        <pawn id="P-J000001" status="Active">
            <amount_given>
                <currency>BGN</currency>
                <value>75.00</value>
            </amount_given>
            <recipient_employee>
                <name>Viktor</name>
                <surname>Petkov</surname>
                <employee_id>E0001</employee_id>
            </recipient_employee>
            <submitter>
                <name>Dimitar</name>
                <surname>Ivanov</surname>
                <ucn>9502029909</ucn>
                <permanent_address>Sofia, Bulgaria</permanent_address>
                <phone_number>0875664446</phone_number>
                <id_card>641290001</id_card>
            </submitter>
            <term>01.04.2022</term>
            <created_at>01.01.2022</created_at>
            <updated_at>01.01.2022</updated_at>
        </pawn>
        <pawn id="P-J000002" status="Active">
            <amount_given>
                <currency>BGN</currency>
                <value>50.00</value>
            </amount_given>
            <recipient_employee>
                <name>Viktor</name>
                <surname>Petkov</surname>
                <employee_id>E0001</employee_id>
            </recipient_employee>
            <submitter>
                <name>Eleonora</name>
                <surname>Todorova</surname>
                <ucn>9003099909</ucn>
                <permanent_address>Plovdiv, Bulgaria</permanent_address>
                <phone_number>0896578546</phone_number>
                <id_card>640105901</id_card>
            </submitter>
            <term>06.06.2022</term>
            <created_at>05.01.2022</created_at>
            <updated_at>10.01.2022</updated_at>
        </pawn>
    </pawns>

</pawnshop>
